# Generated by Django 3.1.3 on 2020-11-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
    ]
