# Generated by Django 3.1.3 on 2020-11-26 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201126_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
