# Generated by Django 3.1.3 on 2020-11-27 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20201127_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Created'),
        ),
    ]
