# Generated by Django 3.1.3 on 2020-11-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20201127_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
