# Generated by Django 3.1.3 on 2021-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
