# Generated by Django 3.1.3 on 2020-11-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='date',
            new_name='created_on',
        ),
    ]
