# Generated by Django 3.1.3 on 2020-11-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201126_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
